name: livrodin
description: Aplicativo de troca e doação de livros.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^1.22.0
  firebase_auth: ^3.9.0
  cloud_firestore: ^3.4.8
  firebase_storage: ^10.3.8
  page_transition: ^2.0.9
  badges: ^2.0.3
  books_finder: ^4.3.0
  easy_debounce: ^2.0.2+1
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  storybook_flutter: ^0.11.2
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/Avenir-Light.ttf
          weight: 300
        - asset: fonts/Avenir-Medium.ttf
          weight: 400
        - asset: fonts/Avenir-Heavy.ttf
          weight: 600
        - asset: fonts/Avenir-Black.ttf
          weight: 800

