// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWMYeFZUFpjfm5k7q-eRJ0OJc30jwdP2c',
    appId: '1:322063612294:web:0a2fefe32790840bf95407',
    messagingSenderId: '322063612294',
    projectId: 'tcc-book',
    authDomain: 'tcc-book.firebaseapp.com',
    storageBucket: 'tcc-book.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL1jhAIrk9t-eCrguJhI_5SJE1KPj_EHA',
    appId: '1:322063612294:android:a218365832497faef95407',
    messagingSenderId: '322063612294',
    projectId: 'tcc-book',
    storageBucket: 'tcc-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxUdv8qZd1Bs54kEeR9hegI1ZvbFLGyNY',
    appId: '1:322063612294:ios:94f8b22c27e84c14f95407',
    messagingSenderId: '322063612294',
    projectId: 'tcc-book',
    storageBucket: 'tcc-book.appspot.com',
    androidClientId: '322063612294-dkakmqj77mdp29eouvit33qo2ho42f6e.apps.googleusercontent.com',
    iosClientId: '322063612294-e4h2ojn8i54l35avv7gdj2jelr3vkgb9.apps.googleusercontent.com',
    iosBundleId: 'com.livrodin.livrodinApp',
  );
}
