/// Flutter icons LivrodinIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LivrodinIcons
///      fonts:
///       - asset: fonts/LivrodinIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class LivrodinIcons {
  LivrodinIcons._();

  static const _kFontFam = 'LivrodinIcons';
  static const String? _kFontPkg = null;

  static const IconData donateIcon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addBook =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
